version: '3.8'

services:
  main-app:
    build:
      context: ./apps/main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - ycempire-network

  admin-app:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - ycempire-network

  bookings-app:
    build:
      context: ./apps/bookings
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - ycempire-network

  rentals-app:
    build:
      context: ./apps/rentals
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - ycempire-network

  links-app:
    build:
      context: ./apps/links
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - ycempire-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - main-app
      - admin-app
      - bookings-app
      - rentals-app
      - links-app
    restart: unless-stopped
    networks:
      - ycempire-network

networks:
  ycempire-network:
    driver: bridge 